POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjIyMiIsImlkIjoiNjFiNDYyNGVlNzgwOWUzYjc1NTkzYjZlIiwiaWF0IjoxNjM5MjExNjM2LCJleHAiOjE2MzkyMTUyMzZ9.Kkuf1fmI4XbyO5N-geAKrtozFhFubj1vlSU_0CODw8o

{
  "title": "Title12",
  "author": "Author",
  "url": "Url",
  "likes": 30,
  "userId": "61b4624ee7809e3b75593b6e"
}